/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py  e 0 > output/out.0 2> output/err.0
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 1 > output/out.1 2> output/err.1
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 2 > output/out.2 2> output/err.2
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 3 > output/out.3 2> output/err.3
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 4 > output/out.4 2> output/err.4
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 5 > output/out.5 2> output/err.5
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 6 > output/out.6 2> output/err.6
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 7 > output/out.7 2> output/err.7
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 8 > output/out.8 2> output/err.8
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 9 > output/out.9 2> output/err.9
/HOME/nscc-gz_jiangli/virtualenv/ht_celery/simtask.py   1 2 3 9 > output/out.10 2> output/err.11
Traceback (most recent call last):
  File "/HOME/nscc-gz_jiangli/virtualenv/ht_celery/run.py", line 28, in <module>
    rs.get()
  File "/HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/lib/python3.4/site-packages/celery/result.py", line 578, in get
    interval=interval, callback=callback, no_ack=no_ack)
  File "/HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/lib/python3.4/site-packages/celery/result.py", line 691, in join_native
    raise value
Exception: ('Exit at code:', 1)
